Name:           ros-indigo-multisense
Version:        3.4.3
Release:        0%{?dist}
Summary:        ROS multisense package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/multisense
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-multisense-bringup
Requires:       ros-indigo-multisense-cal-check
Requires:       ros-indigo-multisense-description
Requires:       ros-indigo-multisense-lib
Requires:       ros-indigo-multisense-ros
BuildRequires:  ros-indigo-catkin

%description
multisense catkin driver

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Feb 12 2015 Maintained by Carnegie Robotics LLC <support@carnegierobotics.com> - 3.4.3-0
- Autogenerated by Bloom

* Fri Jan 30 2015 Maintained by Carnegie Robotics LLC <support@carnegierobotics.com> - 3.4.2-0
- Autogenerated by Bloom

* Tue Dec 30 2014 Maintained by Carnegie Robotics LLC <support@carnegierobotics.com> - 3.4.1-0
- Autogenerated by Bloom

