Name:           ros-kinetic-multisense
Version:        4.0.0
Release:        0%{?dist}
Summary:        ROS multisense package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/multisense
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-multisense-bringup
Requires:       ros-kinetic-multisense-cal-check
Requires:       ros-kinetic-multisense-description
Requires:       ros-kinetic-multisense-lib
Requires:       ros-kinetic-multisense-ros
BuildRequires:  ros-kinetic-catkin

%description
multisense catkin driver

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Feb 06 2017 Maintained by Carnegie Robotics LLC <support@carnegierobotics.com> - 4.0.0-0
- Autogenerated by Bloom

* Thu Sep 08 2016 Maintained by Carnegie Robotics LLC <support@carnegierobotics.com> - 3.4.9-0
- Autogenerated by Bloom

* Sat Aug 27 2016 Maintained by Carnegie Robotics LLC <support@carnegierobotics.com> - 3.4.7-0
- Autogenerated by Bloom

